### ISSUE TITLE
dual license with bsd?

### ISSUE THREAD

**Issue by ahundt** [giacomodabisias/libfreenect2pclgrabber#10]
Any chance you might be willing to dual license this with bsd in addition to gpl? I have a bsd licensed project where I think I'd like to use it which isn't gpl compatible.

http://choosealicense.com/licenses/bsd-2-clause/

**Comment by giacomodabisias** [comment]
Hi,
what Kind of project?

**Comment by ahundt** [comment]
https://github.com/ahundt/grl

**Comment by giacomodabisias** [comment]
ok, feel free to use it

2015-10-30 21:06 GMT+01:00 Andrew Hundt <notifications@github.com>:

> https://github.com/ahundt/grl
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/giacomodabisias/libfreenect2pclgrabber/issues/10#issuecomment-152638835>
> .
>



-- 
Ing G. Dabisias, PhD Student
PERCRO, (Laboratory of Perceptual Robotics)
Scuola Superiore Sant'Anna
via Luigi Alamanni 13D, San Giuliano Terme 56010 (PI), Italy
mob.: +39 3480839095

**Comment by ahundt** [comment]
thanks!
