### ISSUE TITLE
Is it possible to apply to multi Kinects ?

### ISSUE THREAD

**Issue by moonsh** [giacomodabisias/libfreenect2pclgrabber#14]
Hello

First of all, thank you for sharing your hard work.

I am doing study using multi kinects . By the way, I got a question.

I have succeeded using a single kinect but I have faced problem to set the second kinect.

It wasn't work properly. So I am curious whether multi kinects are possible or not. 

And I have one more question. 

The values x,y and z which I got using PCL are same as output of Libfreenect2 data ?

Thank you.

**Comment by giacomodabisias** [comment]
Thanks,
What is the problem?
Il 25/Feb/2016 09:05, "moonsh" <notifications@github.com> ha scritto:

**Comment by moonsh** [comment]
Is it possible to apply to multi Kinects ??  I have faced a error when I try use two kinects .

And I have one more question.

The values x,y and z which I got using PCL are same as output of Libfreenect2 data ?

**Comment by giacomodabisias** [comment]
Hi.
Yes. What is the error message?
Yes
Il 25/Feb/2016 11:21 AM, "moonsh" <notifications@github.com> ha scritto:

**Comment by moonsh** [comment]
Sorry for not detail explanation.

I just declared second  K2G class for second Kinect . 
  K2G k2g(freenectprocessor ,   0);
  K2G k2g2(freenectprocessor, 1);
0 is Frist kinect, 1 is Second kinect

and then I declared second cloud like this.
  boost::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB>> cloud2;

and then I followed existing coding .

This coding is building well but exe doesn't work

I think there must be something more I need to declare.

**Comment by giacomodabisias** [comment]
Exe?  Are you on windows?
Il 25/Feb/2016 11:42, "moonsh" <notifications@github.com> ha scritto:

**Comment by moonsh** [comment]
Yes windows I used visual studio

**Comment by giacomodabisias** [comment]
If you want to open two kinects you have to open them by serial id. I have
to add that, I forgot.
Have a look at this code on how to do it. I will add that feature later
today if you want to wait for it

2016-02-25 11:45 GMT+01:00 moonsh <notifications@github.com>:

> Yes windows I used visual studio
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/giacomodabisias/libfreenect2pclgrabber/issues/14#issuecomment-188722364>
> .
>



-- 
Ing G. Dabisias, PhD Student
Percro Lab, (Laboratory of Perceptual Robotics)
Scuola Superiore Sant'Anna
via Luigi Alamanni 13D, San Giuliano Terme 56010 (PI), Italy
mob.: +39 3480839095
skype: giacomo.dabisias2

**Comment by moonsh** [comment]
Is this right approach ?

K2G k2g(freenectprocessor , 0);
K2G k2g2(freenectprocessor, 1);
0 is Frist kinect, 1 is Second kinect
	

K2G(processor p, int snumber, bool mirror = false): mirror_(mirror), listener_(libfreenect2::Frame::Color | libfreenect2::Frame::Ir | libfreenect2::Frame::Depth), 
	                                       undistorted_(512, 424, 4), registered_(512, 424, 4), big_mat_(1920, 1082, 4), qnan_(std::numeric_limits<float>::quiet_NaN())

 serial_ = freenect2_.getDeviceSerialNumber(snumber);

**Comment by giacomodabisias** [comment]
no, that value is mirroring as stated.

2016-02-25 12:58 GMT+01:00 moonsh <notifications@github.com>:

> Is this right approach ?
>
> K2G k2g(freenectprocessor , 0);
> K2G k2g2(freenectprocessor, 1);
> 0 is Frist kinect, 1 is Second kinect
>
> K2G(processor p, int snumber, bool mirror = false): mirror_(mirror),
> listener_(libfreenect2::Frame::Color | libfreenect2::Frame::Ir |
> libfreenect2::Frame::Depth),
> undistorted_(512, 424, 4), registered_(512, 424, 4), big_mat_(1920, 1082,
> 4), qnan_(std::numeric_limits::quiet_NaN())
>
> serial_ = freenect2_.getDeviceSerialNumber(snumber);
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/giacomodabisias/libfreenect2pclgrabber/issues/14#issuecomment-188753551>
> .
>



-- 
Ing G. Dabisias, PhD Student
Percro Lab, (Laboratory of Perceptual Robotics)
Scuola Superiore Sant'Anna
via Luigi Alamanni 13D, San Giuliano Terme 56010 (PI), Italy
mob.: +39 3480839095
skype: giacomo.dabisias2

**Comment by giacomodabisias** [comment]
Now you should be able to use multiple kinect2 by pulling the last version. You need to pass as first parameter the processor, second if you want mirroring and third a string with the serial number od the device

**Comment by moonsh** [comment]
Firstly, Thanks a lot.

Sorry for keep asking 

I tried selecting Kinect but it said there is declaration error

I did like below to select 502394541942 kinect and no mirroring  but it seems there is mistake.

 K2G k2g(freenectprocessor, false, 502394541942);

**Comment by giacomodabisias** [comment]
You have to do a git pull

**Comment by moonsh** [comment]
I downloaded latest version

**Comment by giacomodabisias** [comment]
So what is the exact error?

**Comment by moonsh** [comment]
K2G k2g(freenectprocessor, false, 502394541942);

Parameter types should be  (processor, bool, double double  ) 

I think 502394541942 is problem.

**Comment by giacomodabisias** [comment]
Yeah, the last parameter should be passed as string which is more generic so do:
K2G k2g(freenectprocessor, false, "502394541942");

**Comment by moonsh** [comment]
Ah thank you very much. It was a silly question. 

By the way , what does mirroring mean ?

**Comment by giacomodabisias** [comment]
it flips depth and color

**Comment by moonsh** [comment]
Thanks a lot . I will close this issue

**Comment by moonsh** [comment]
It works well but frame speed is getting slower and slower..

**Comment by giacomodabisias** [comment]
Ok so both kinect work at the same time right? Could you check if memory consumption of the executable is constant or growing? could be a memory leak

**Comment by moonsh** [comment]
Yes right , There is no growing memory and cpu.  They are constant.

Maybe this speed is maximum ?

**Comment by giacomodabisias** [comment]
I will test it and let you know; just got a second kinect2

**Comment by giacomodabisias** [comment]
I am getting 
[Error] [protocol::CommandTransaction] bulk transfer failed: LIBUSB_ERROR_IO Input/Output Error

could you share your code to have a look?

**Comment by giacomodabisias** [comment]
Works if you show all in the same viewer. Its a vtk problem with multiple viewers

**Comment by giacomodabisias** [comment]
I uploaded an example working with multiple kinects

**Comment by moonsh** [comment]
I am sorry to ask you again

I tried example and computer tells it isn't executable

**Comment by giacomodabisias** [comment]
SOrry I can't understand the problem. Could you reformulate?

**Comment by moonsh** [comment]
I just tried your multiple kinects example but it doesn't work.

**Comment by giacomodabisias** [comment]
What is the error and what arguments are you passing to  the executable?

**Comment by moonsh** [comment]
Error message : It is not executable.    I used your code 
    
  boost::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB>> cloud_1;
  boost::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB>> cloud_2;
  K2G k2g_1(freenectprocessor, argc == 5 ? true : false, argv[2]); 
  K2G k2g_2(freenectprocessor, argc == 5 ? true : false, argv[3]); 

  std::cout << "getting cloud" << std::endl;
  cloud_1 = k2g_1.getCloud();
  cloud_2 = k2g_2.getCloud();

  cloud_1->sensor_orientation_.w() = 0.0;
  cloud_1->sensor_orientation_.x() = 1.0;
  cloud_1->sensor_orientation_.y() = 0.0;
  cloud_1->sensor_orientation_.z() = 0.0;

  cloud_2->sensor_orientation_.w() = 0.0;
  cloud_2->sensor_orientation_.x() = 1.0;
  cloud_2->sensor_orientation_.y() = 0.0;
  cloud_2->sensor_orientation_.z() = 0.0;

**Comment by giacomodabisias** [comment]
what arguments are you passing to the executable? can you write the exact execution line?

**Comment by moonsh** [comment]
sorry for late reply 

I wrote like this 

MultKinect2Grabber.exe 51169242542 502394541942

**Comment by giacomodabisias** [comment]
Are you on windows? Did you build again the multi_test?

**Comment by moonsh** [comment]
Yes I am using Windows 

Yes I built again

**Comment by giacomodabisias** [comment]
The grabber was developed for Linux so I am not sure where the problem could be. 
Is the single grabber working?
The arguments have to be "processor serial1 serial2" so try to execute it using the correct arguments.
 0,1,2,3 correspond to CPU, OPENCL, OPENGL, CUDA

**Comment by moonsh** [comment]
Ah I see.

Yes single grabber is working well

I wrote this but this one also doesn't work.
"processor serial1 serial2"

**Comment by giacomodabisias** [comment]
You have to write MultKinect2Grabber.exe  0 51169242542 502394541942

**Comment by moonsh** [comment]
Ah yes I already tried like that 
MultKinect2Grabber.exe 0 51169242542 502394541942

It doesn't work

**Comment by giacomodabisias** [comment]
and the error is still the same?

**Comment by moonsh** [comment]
Yes same

**Comment by giacomodabisias** [comment]
No idea, its a Windows or build error.

**Comment by jiaojialulu** [comment]
I succeed on windows.
First of all to ensure that you can use two kinects.
And I can only run this code in release mode.
Then you should set "Stack Reserve Size" of the project to a big number ,I set 999999.

**Comment by giacomodabisias** [comment]
Great to hear that! :)

**Comment by ghost** [comment]
Hi, how to  declare two kinect. 
K2G k2g(freenectprocessor, 0,"875561444447");
 K2G k2g(freenectprocessor, 1,"543402634447");
This declare doesn't work, or where to specify at least processor and one serial?
Thanks.

**Comment by giacomodabisias** [comment]
Hi, you are declaring twice the same variable

**Comment by ghost** [comment]
Thanks for answer.
Change on two type variable:
```
K2G k2g(freenectprocessor, 0,"875561444447");
 K2G k2g2(freenectprocessor, 1,"543402634447");
  std::cout << "getting cloud" << std::endl;
  cloud = k2g.getCloud();
cloud = k2g2.getCloud(); 
```
results:

> [Info] [Freenect2DeviceImpl] opening...
> [Info] [Freenect2DeviceImpl] transfer pool sizes rgb: 20*16384 ir: 60*8*33792
> [Info] [Freenect2DeviceImpl] opened
> [Info] [Freenect2DeviceImpl] starting...
> [Error] [protocol::CommandTransaction] bulk transfer failed: LIBUSB_ERROR_IO Input/Output Error
> getting cloud
> [Info] [OpenGLDepthPacketProcessor] avg. time: 19.2322ms -> ~51.9961Hz
> [Info] [VaapiRgbPacketProcessor] avg. time: 9.22728ms -> ~108.374Hz
> 

I think this is my fault because im using test.cpp. How to use code in Multi_test.cpp? How to specify least processor and one serial? 
I would be very grateful for your help.
Thanks

**Comment by giacomodabisias** [comment]
Just use the MultiKinect2Grabber binary which you cna build from the cmake

**Comment by ghost** [comment]
In Multiple i got error.

> Syntax is: ./MultiKinect2Grabber [-processor 0|1|2] -processor options 0,1,2,3 correspond to CPU, OPENCL, OPENGL, CUDA respectively
> followed by the kinect2 serials and a last 1 for mirroring
> Press 's' to store both clouds and color images.
> Press 'x' to store both calibrations.
> Wrong syntax! specify at least processor and one serial: 1
What to do "argc"?

**Comment by giacomodabisias** [comment]
/MultiKinect2Grabber [-processor 0|1|2] -processor options 0,1,2,3 correspond to CPU, OPENCL, OPENGL, CUDA respectively
this is telling you what to run. What are you running?
