### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by hanshammel1337** [giacomodabisias/libfreenect2pclgrabber#19]
hello,

i got an error while `cmake ..` in build folder. changed nothing, just git clone. i have  successfully installed libfreenect2: protonect and also iai_kinect2 as ros bridge are working fine.

it seems there is trouble with the include dirs and cmake. in other issues you mentioned to `sudo make install` libfreenect2. this seems to be bad because this is not the standard installation advise from the github page for libfreenect2.

does `find_package(Freenect2  REQUIRED)` fail?
can you please help

greetings

-----------------------------------------------------------------------------------------------
ben@ben-laptop:~/libfreenect2pclgrabber/build$ cmake ..
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   thread
--   date_time
--   iostreams
--   serialization
-- checking for module 'openni-dev'
--   package 'openni-dev' not found
-- checking for module 'openni-dev'
--   package 'openni-dev' not found
-- checking for module 'openni-dev'
--   package 'openni-dev' not found
-- looking for PCL_COMMON
-- looking for PCL_OCTREE
-- looking for PCL_IO
-- looking for PCL_KDTREE
-- looking for PCL_SEARCH
-- looking for PCL_SAMPLE_CONSENSUS
-- looking for PCL_FILTERS
-- looking for PCL_FEATURES
-- looking for PCL_KEYPOINTS
-- looking for PCL_GEOMETRY
-- looking for PCL_SEGMENTATION
-- looking for PCL_VISUALIZATION
-- looking for PCL_OUTOFCORE
-- looking for PCL_REGISTRATION
-- looking for PCL_RECOGNITION
-- looking for PCL_SURFACE
-- looking for PCL_PEOPLE
-- looking for PCL_TRACKING
-- looking for PCL_APPS
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
FREENECT2_INCLUDE_DIRS
   used as include directory in directory /home/ben/libfreenect2pclgrabber
   used as include directory in directory /home/ben/libfreenect2pclgrabber
FREENECT2_LIBRARY
    linked by target "Kinect2Grabber" in directory /home/ben/libfreenect2pclgrabber
    linked by target "MultiKinect2Grabber" in directory /home/ben/libfreenect2pclgrabber

-- Configuring incomplete, errors occurred!
See also "/home/ben/libfreenect2pclgrabber/build/CMakeFiles/CMakeOutput.log".
ben@ben-laptop:~/libfreenect2pclgrabber/build$

**Comment by giacomodabisias** [comment]
Hi,
you did not install libfreenect2 in /usr/local so either go into the build folder of libfreenect2 and execute sudo make install or if you have installed it in a separate prefix go into the grabber build folder and execute ccmake .. and set the freenect2 variables

**Comment by hanshammel1337** [comment]
thank you! following the libfreenect2 standard installation, this should do the work in CMakeLists.txt from libfreenect2pclgrabber:
`set(FREENECT2_INCLUDE_DIRS "/home/$ENV{USER}/freenect2/include")`
`set(FREENECT2_LIBRARY "/home/$ENV{USER}/freenect2/lib/libfreenect2.so")`

nevertheless, now it works with CPU processor but not with `Processor freenectprocessor = OPENCL;` i changed `OFF` to  `ON` in CMakeLists.txt fpr `WITH_OPENCL`.
have you tested it with OPENCL? libfreenect2 with iai_kinect run good with openCL on my machine, but the grabber does not :(

-----------------------------------------------------------
ben@ben-laptop:~/libfreenect2pclgrabber/build$ ./Kinect2Grabber
Syntax is: ./Kinect2Grabber [-processor 0|1|2] -processor options 0,1,2,3 correspond to CPU, OPENCL, OPENGL, CUDA respectively
Press 's' to store a cloud
Press 'x' to store the calibrations.
[Info] [Freenect2Impl] enumerating devices...
[Info] [Freenect2Impl] 12 usb devices connected
[Info] [Freenect2Impl] found valid Kinect v2 @2:3 with serial 006870123456
[Info] [Freenect2Impl] found 1 devices
creating OpenCL processor
[Error] [OpenCLDepthPacketProcessorImpl] cl::Platform::get(&platforms): -1001
[Error] [OpenCLAllocator] b->buffer = cl::Buffer(context, CL_MEM_WRITE_ONLY | CL_MEM_ALLOC_HOST_PTR, size, NULL, &err): -34
[Error] [OpenCLAllocator] b->buffer = cl::Buffer(context, CL_MEM_WRITE_ONLY | CL_MEM_ALLOC_HOST_PTR, size, NULL, &err): -34
[Error] [OpenCLAllocator] b->buffer = cl::Buffer(context, CL_MEM_READ_ONLY | CL_MEM_ALLOC_HOST_PTR, size, NULL, &err): -34
[Info] [Freenect2DeviceImpl] opening...
[Info] [Freenect2DeviceImpl] transfer pool sizes rgb: 20*16384 ir: 60*8*33792
[Info] [Freenect2DeviceImpl] opened
[Info] [Freenect2DeviceImpl] starting...
[Error] [OpenCLDepthPacketProcessorImpl] OpenCLDepthPacketProcessor is not initialized!
[Error] [OpenCLDepthPacketProcessorImpl] OpenCLDepthPacketProcessor is not initialized!
[Error] [OpenCLDepthPacketProcessorImpl] OpenCLDepthPacketProcessor is not initialized!
[Info] [Freenect2DeviceImpl] submitting rgb transfers...
[Info] [Freenect2DeviceImpl] submitting depth transfers...
[Error] [DepthPacketStreamParser] Packet buffer is NULL
[Error] [DepthPacketStreamParser] Packet buffer is NULL
[Error] [DepthPacketStreamParser] Packet buffer is NULL

**Comment by giacomodabisias** [comment]
Hi,
Did you try to execute the grabber passing 0, 1, 2 and so on to see if the other processors work?

**Comment by hanshammel1337** [comment]
Yes i did.
0 = CPU, works fine, but slow.
1 = should be opencl, but falls back to `creating Cpu processor`
2 = should be opengl, but falls back to `creating Cpu processor` (opengl not working on my machine)

and when i  hardcode opencl as processor in test.cpp as written in my previous post, the output is like posted there.

**Comment by giacomodabisias** [comment]
Did you also test CUDA?

Il 09 Ago 2016 10:03, "Benjamin" <notifications@github.com> ha scritto:

**Comment by giacomodabisias** [comment]
Probably Protonen uses the opencl lib inside of the libfreenect2 folder. Did you install opencv on you system? I think the grabber can't find the opencl lib at runtime

**Comment by hanshammel1337** [comment]
I didn't test CUDA because my system has amd graphic card.
Yes, opencv is installed in version 2.4.8

**Comment by giacomodabisias** [comment]
Sorry I meant opencl...autocorrect
