### ISSUE TITLE
pure virtual method called terminate called without an active exception

### ISSUE THREAD

**Issue by nomi321** [giacomodabisias/libfreenect2pclgrabber#20]
how can i get rid of this error? which thing is causing the error.

**Comment by nomi321** [comment]
i am using the following portion of your grabber to grab point cloud using kinect 2

boost::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB>> cloud;
	  Processor freenectprocessor = OPENGL;
	  K2G k2g(freenectprocessor);
	  std::cout << "getting cloud" << std::endl;
	  cloud = k2g.getCloud();

and I want to use this cloud for further processing. 

and this is the output i get

[Info] [Freenect2DeviceImpl] opening...
[Info] [Freenect2DeviceImpl] transfer pool sizes rgb: 20*16384 ir: 60*8*33792
[Info] [Freenect2DeviceImpl] opened
[Info] [Freenect2DeviceImpl] starting...
[Info] [Freenect2DeviceImpl] submitting rgb transfers...
[Info] [Freenect2DeviceImpl] submitting depth transfers...
[Info] [Freenect2DeviceImpl] started
[Info] [RgbPacketStreamParser] packetsize or sequence doesn't match!
getting cloud
[Info] [DepthPacketStreamParser] 7 packets were lost
PointCloud representing the Cluster: 1158 data points.
[Info] [Freenect2DeviceImpl] closing...
[Info] [Freenect2DeviceImpl] stopping...
[Info] [Freenect2DeviceImpl] canceling rgb transfers...
pure virtual method called
terminate called without an active exception

**Comment by giacomodabisias** [comment]
Hi,
Did you build the grabber with OPENGL support?

Il 12 Ago 2016 09:36, "nomi321" <notifications@github.com> ha scritto:

**Comment by nomi321** [comment]
yes sir

**Comment by nomi321** [comment]
i just want that my code just take current point cloud at the moment and then stop taking further frames and then process the cloud. how can i accomplish this ?

**Comment by giacomodabisias** [comment]
Just don't do a cyle but grab one cloud
