### ISSUE TITLE
Is it possible to build libfreenect2pclgrabber on a system without OpenGL?

### ISSUE THREAD

**Issue by jpers1** [giacomodabisias/libfreenect2pclgrabber#26]
I am building libfreenect2pclgrabber on **Odroid XU4 platform** (ARM, http://www.hardkernel.com/main/products/prdt_info.php ), running **Ubuntu 16.04**.  Built libfreenect2 without issues, but without OpenGL support, since the board supports only OpenGL ES (but it supports OpenCL).  Protonect works in CPU and OpenCL mode, but there is no display, since it needs OpenGL to show the video.

However, when trying to build libfreenect2pclgrabber, the compilation fails:

`odroid@odroid:~/libfreenect2pclgrabber/build$ make
Scanning dependencies of target MultiKinect2Grabber
[ 25%] Building CXX object CMakeFiles/MultiKinect2Grabber.dir/multi_test.cpp.o
In file included from /home/odroid/libfreenect2pclgrabber/multi_test.cpp:19:0:
/home/odroid/libfreenect2pclgrabber/include/k2g.h: In constructor âK2G::K2G(Processor, bool, std::__cxx11::string)â:
/home/odroid/libfreenect2pclgrabber/include/k2g.h:94:47: error: expected type-specifier
      dev_ = freenect2_.openDefaultDevice (new libfreenect2::OpenGLPacketPipeline ());
                                               ^
/home/odroid/libfreenect2pclgrabber/include/k2g.h:96:48: error: expected type-specifier
      dev_ = freenect2_.openDevice (serial, new libfreenect2::OpenGLPacketPipeline ());
                                                ^
In file included from /home/odroid/libfreenect2pclgrabber/multi_test.cpp:20:0:
/usr/include/pcl-1.7/pcl/visualization/cloud_viewer.h: At global scope:
/usr/include/pcl-1.7/pcl/visualization/cloud_viewer.h:202:14: warning: âtemplate<class> class std::auto_ptrâ is deprecated [-Wdeprecated-declarations]
         std::auto_ptr<CloudViewer_impl> impl_;
              ^
In file included from /usr/include/c++/5/memory:81:0,
                 from /usr/include/boost/config/no_tr1/memory.hpp:21,
                 from /usr/include/boost/smart_ptr/shared_ptr.hpp:23,
                 from /usr/include/boost/shared_ptr.hpp:17,
                 from /usr/include/pcl-1.7/pcl/PCLHeader.h:10,
                 from /usr/include/pcl-1.7/pcl/point_cloud.h:48,
                 from /home/odroid/libfreenect2pclgrabber/include/k2g.h:29,
                 from /home/odroid/libfreenect2pclgrabber/multi_test.cpp:19:
/usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
CMakeFiles/MultiKinect2Grabber.dir/build.make:62: recipe for target 'CMakeFiles/MultiKinect2Grabber.dir/multi_test.cpp.o' failed
make[2]: *** [CMakeFiles/MultiKinect2Grabber.dir/multi_test.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/MultiKinect2Grabber.dir/all' failed
make[1]: *** [CMakeFiles/MultiKinect2Grabber.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
odroid@odroid:~/libfreenect2pclgrabber/build$
`
with the key problem being apparently

`/home/odroid/libfreenect2pclgrabber/include/k2g.h:94:47: error: expected type-specifier
      dev_ = freenect2_.openDefaultDevice (new libfreenect2::OpenGLPacketPipeline ());`

Now, since there is no OpenGL, this line is problematic in any case - but I am not sure it is the cause of the problem. I tried to disable OpenGL with `ccmake`, but there is no option to do so.

Any suggestions?

**Comment by giacomodabisias** [comment]
Hi,

yes.


I did not add that option to the cmake but you can just uncomment the
opengl part in the grabber include file.

Something like:

case OPENGL:
std::cout << "creating OpenGL processor" << std::endl;
if (serial.empty())
dev_ = freenect2_.openDefaultDevice (new libfreenect2::OpenGLPacketPipeline
());
else
dev_ = freenect2_.openDevice (serial, new libfreenect2::OpenGLPacketPipeline
());
break;

2017-07-16 23:49 GMT+01:00 jpers1 <notifications@github.com>:

**Comment by margokhokhlova** [comment]
Hello! Sorry, I am trying to build the project on for VS2014(15), on windows 8.1. freenect is working, but then this project is either not compiling with an error: C2039	'OpenGLPacketPipeline': is not a member of 'libfreenect2'	Kinect2Grabber. but all the dependencies are attached.  And with VS2012 and pre-built freenect, I can compile project, but still getting a crash after the phrase: open openGL Processor... 
Please, give me a hint what can be done if possible. thanks a lot!

**Comment by giacomodabisias** [comment]
Hi
The code was developed for linux. Anyway try to just disable the opengl processor in the ccmake file and then compile again.

**Comment by margokhokhlova** [comment]
Thank you for your answer! And for the code shared! >**<
I finally managed to build it, with opengl support, it works on windows. So far I am trying to  look through the code, but I have a question ->  you have an option to store the yaml calibration file, so I assume I can align 2 resulting point clouds later after the aqusition?
