### ISSUE TITLE
Error of registration

### ISSUE THREAD

**Issue by yincanben** [giacomodabisias/libfreenect2pclgrabber#3]
I want to use it to grab a PointCloud, But I found the RGB image and Depth Image can't register together, Can you help me to resolve this problem?

**Comment by giacomodabisias** [comment]
Hello,
you need to do a new calibration first to align depth and rgb

2015-06-19 3:55 GMT+02:00 yincanben <notifications@github.com>:

> I want to use it to grab a PointCloud, But I found the RGB image and Depth
> Image can't register together, Can you help me to resolve this problem?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/giacomodabisias/libfreenect2pclgrabber/issues/3>.
>



-- 
G. Dabisias, PhD Student
PERCRO, (Laboratory of Perceptual Robotics)
Scuola Superiore Sant'Anna
via Luigi Alamanni 13D, San Giuliano Terme 56010 (PI), Italy
mob.: +39 3480839095
