### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by jiaojialulu** [giacomodabisias/libfreenect2pclgrabber#7]
hello, when we cmake this code libfreenect2pclgrabber in Cmake,  we get this problem:

 CMake Error at D:/applications/CMake/share/cmake-3.2/Modules/FindPkgConfig.cmake:548 (message):
None of the required 'glfw3' found
Call Stack (most recent call first):
  CMakeLists.txt:10 (pkg_search_module)

What should I do?  Can you help me.

**Comment by giacomodabisias** [comment]
install glfw3 with apt-get

2015-10-16 14:12 GMT+02:00 jiaojialulu <notifications@github.com>:

> hello, when we cmake this code libfreenect2pclgrabber in Cmake, we get
> this problem:
>
> CMake Error at
> D:/applications/CMake/share/cmake-3.2/Modules/FindPkgConfig.cmake:548
> (message):
> None of the required 'glfw3' found
> Call Stack (most recent call first):
> CMakeLists.txt:10 (pkg_search_module)
>
> What should I do? Can you help me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/giacomodabisias/libfreenect2pclgrabber/issues/7>.
>



-- 
G. Dabisias, PhD Student
PERCRO, (Laboratory of Perceptual Robotics)
Scuola Superiore Sant'Anna
via Luigi Alamanni 13D, San Giuliano Terme 56010 (PI), Italy
mob.: +39 3480839095

**Comment by jiaojialulu** [comment]
Sorry,but I'm a greenhand, and my system is windows 10.I already had this:
![image](https://cloud.githubusercontent.com/assets/14901098/10541888/eb671c08-7446-11e5-8cb0-07384454b46f.png)
And my system environment variable was setted this:
GLFW
E:\cvlab\Documents\a grabber for the kinect2 which returns a registered pcl point cloud\glfw

Actually,I want to use kinectv2CalibrationCapture this repository, so should I complile libfreenect2pclgrabber or freenect_cloud_grabber at first?

THANK YOU VERY MUCH!!!

**Comment by giacomodabisias** [comment]
The project is tested only for linux,
can't help you on windows,
sorry

2015-10-16 14:57 GMT+02:00 jiaojialulu <notifications@github.com>:

> Sorry,but I'm a greenhand, and my system is windows 10.I already had this:
> [image: image]
> <https://cloud.githubusercontent.com/assets/14901098/10541888/eb671c08-7446-11e5-8cb0-07384454b46f.png>
> And my system environment variable was setted this:
> GLFW
> E:\cvlab\Documents\a grabber for the kinect2 which returns a registered
> pcl point cloud\glfw
>
> Actually,I want to use kinectv2CalibrationCapture this repository, so
> should I complile libfreenect2pclgrabber or freenect_cloud_grabber at first?
>
> THANK YOU VERY MUCH!!!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/giacomodabisias/libfreenect2pclgrabber/issues/7#issuecomment-148709934>
> .
>



-- 
G. Dabisias, PhD Student
PERCRO, (Laboratory of Perceptual Robotics)
Scuola Superiore Sant'Anna
via Luigi Alamanni 13D, San Giuliano Terme 56010 (PI), Italy
mob.: +39 3480839095

**Comment by jiaojialulu** [comment]
thanks all the same. I will have a try on windows.
